"""Initial

Revision ID: d6ce6b04b042
Revises: 
Create Date: 2022-06-15 10:14:10.277668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d6ce6b04b042"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", postgresql.UUID(), nullable=False, comment="UUID"),
        sa.Column("username", sa.String(length=128), nullable=False, comment="Имя пользователя"),
        sa.Column("password", sa.String(length=128), nullable=False, comment="Пароль пользователя"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="Дата и время создания записи",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True, comment="Дата и время обновления записи"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
